# Generated by Django 6.0.6 on 2026-06-05 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_book_author_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='jinsi',
            field=models.CharField(blank=True, choices=[('Erkak', 'Erkak'), ('Ayol', 'Ayol')], max_length=245, null=True),
        ),
    ]
