# Generated by Django 6.0.6 on 2026-06-17 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_author_jinsi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=245)),
                ('brand', models.CharField(max_length=245)),
                ('ram', models.CharField(max_length=245)),
                ('memory', models.CharField(max_length=245)),
                ('video_card', models.CharField(max_length=245)),
            ],
        ),
    ]
